import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Poppins} from "next/font/google"
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";

const poppins = Poppins({
  subsets: ["latin"], // penting biar support latin chars
  weight: ["400", "500", "600", "700"], // pilih variasi sesuai kebutuhan
  variable: "--font-poppins", // custom CSS variable biar bisa dipakai di Tailwind
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LapCare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={poppins.variable}
      >
        <Providers/>
        {children}
      </body>
    </html>
  );
}
